### PR TITLE
make min and uglify dependent on --production flag

### PR DESCRIPTION
**Pull request by etcook**
I didn't see a dev branch, so I'm PR'ing to master

-- added yargs, gulp-if and minifyCSS to dependencies
-- made minification of css (sass) dependent on --production flag
-- made uglification of js dependent on --production flag

In reference to zurb/foundation-apps#406 and https://github.com/zurb/foundation-apps-template/pull/19

### CODE REVIEW

**Comment by gakimball** [comment]
Hey, sorry we let this get super stale. I'm going to re-implement your changes with the newest version of the Gulpfile.

**Comment by etcook** [comment]
@gakimball Awesome. F4A is really coming along guys. Thanks for all that you do.

**Comment by gakimball** [comment]
Closing in favor of 1a9f6a7fed9ac68f753d6a7e98aada88b0e51b24, which implements this change.

**Comment by gakimball** [comment]
@etcook It's our pleasure :) Thanks for contributing!

**Pull request closed without merging**
