### PR TITLE
Jade Templates

### PR DESCRIPTION
**Pull request by resistdesign**
Add the ability to use Jade templates as well as HTML.

### CODE REVIEW

**Comment by resistdesign** [comment]
Just out of curiosity, when do you normally look at these PRs?

**Comment by resistdesign** [comment]
BUMP! :)

**Comment by gakimball** [comment]
Hey! Sorry for not getting to this sooner. To answer your question, we usually review things on Friday, but we didn't get a chance to last week. Today we reviewed the PRs for the template stack, and we aren't going to merge any in right now. The template project is meant for beginners, or people just trying out the framework, so we want it to be as simple as possible, which means only core features (Sass compilation, JS uglifying, etc.) and as few moving parts as possible.

Basically we want to keep it to only features that a majority of our users will benefit from. If you're savvy enough to want to use extra features like Jade templating, you're savvy enough to add them yourself ;) We'll be sticking to this philosophy for Foundation for Sites 6 as well, which will include a static site generator.

That being said, today we talked about how we can better document the template project for Foundation for Apps, and one thing we could do is include "recipes" that explain how to bolt on extra features to the template. This could be one such example.

**Comment by resistdesign** [comment]
@gakimball Thank you for getting back to me. I was actually starting to think that myself. But what I'm thinking now is can we add a setting for choosing an app setup/template? The default being this one of course. That would just make it super easy to get some advanced functionality that developers might commonly use.

**Comment by gakimball** [comment]
We've talked about doing multiple templates. We have that for the Foundation 5 CLI, where you can pick between Compass vs. Grunt for your build process. Right now for Foundation 6 we're looking at having a "simple" template, kinda like the current ones, and an "advanced" one that is a static site generator.

In general, the purpose of the CLI is to quickly spin up a project without much thought. As far as configuration stuff goes, I think our main concern there is not accidentally recreating Yeoman ;) There are a lot of awesome generators for Foundation 5 right now, and we'd love to see the same for Foundation for Apps.

I keep thinking I'll learn how Yeoman works, and then I'd just make one myself. You could probably make a good one using this template as a baseline, and add options for HTML templating, linting, CoffeeScript, etc.

**Comment by gakimball** [comment]
*Hot update*, I started writing a Yeoman generator that uses this template, but optionally supports CoffeeScript, ES6, Jade, Haml, Slim, and Ruby Sass. It'll probably be done in the next few days.

**Comment by resistdesign** [comment]
Awesome! What's Slim?

-----Original Message-----

**Comment by AntJanus** [comment]
I think Slim is a Ruby templating engine: http://slim-lang.com/

**Comment by gakimball** [comment]
Yep! gulp-slim taps into the Ruby gem, while Haml and Jade both have Node implementations.

Here's the repo: [generator-foundation-apps](https://github.com/gakimball/generator-foundation-apps). It's not finished, and also not on npm because somebody reserved `generator-foundation-apps` and isn't using it :< So I'll see if that guy wants to help out.

Should be ready in the next few days.

**Comment by resistdesign** [comment]
Maybe there should be a project template that works well with webpack. That makes packing your app dead simple and leaves you open to pretty much any advanced stuff you want to do later.

**Comment by resistdesign** [comment]
I mean the future of web UI is pretty much Foundation Apps w/ Angular and WebPack. Gulp is about to join Grunt and Browserify on the dusty old shelf. And to be honest, I think a CLI that pulls a selected Repo is way easier and smarted than having to build and *maintain* some custom code in a Yeoman generator. If you really think about it, you just make a new base project and commit it, no additional, unnecessary coding required or anything like that to integrate a new project template concept into your generator. Yeoman = BAD. :)

**Pull request closed without merging**
