### PR TITLE
Make min and uglify dependent on --production flag

### PR DESCRIPTION
**Pull request by etcook**
I didn't see a dev branch, so I'm PR'ing to master

-- added yargs, gulp-if and minifyCSS to dependencies
-- made minification of css (sass) dependent on --production flag
-- made uglification of js dependent on --production flag

In reference to https://github.com/zurb/foundation-apps/issues/406

### CODE REVIEW

**Comment by gakimball** [comment]
Nice, thanks for putting it together! My only suggestion is you could remove `gulp-minify-css` and instead control the CSS output using the options passed to `node-sass`. Something like this:

```js
return gulp.src('client/assets/scss/app.scss')
  .pipe(sass({
    loadPath: sassPaths,
    style: (production ? 'compressed' : 'nested'),
    bundleExec: true
  }))
  .pipe(/* ... */)
```

The end result is the same, it's just one less library to load.

**Comment by etcook** [comment]
@gakimball I add minifyCSS to almost all of my projects to handle vendor concat + minification (if it isn't minified already). It would seem like most projects would end up requiring it. However, if you want to keep it lean, I can definitely move that out, set it up in sass, and just assume they'll add minifyCSS anyways.

**Comment by gakimball** [comment]
How does minifyCSS differ from the built-in compression Sass will do? I'm not opposed to adding it, just wondering what it does different.

**Comment by etcook** [comment]
@gakimball Now that you mention it, likely nothing. We could presumably just run the vendor CSS through the sass parser separately, even though it's not SASS.

**Comment by gakimball** [comment]
Ohh, I was totally forgetting situations where you're using vendor files from plugins that use plain CSS.

So the issue there is that Sass can't `@import` a plain CSS file (this is coming in Sass 4.0), which is why you'd need to manually inject it into a Gulp stream to get it into a finished file. But if the plugin doesn't distribute a minified CSS file, you need another means to compress it.

Now I get what you're saying. But the pipe would have to be restructured to insert plain CSS after the Sass is done being processed.

We could accommodate this use case, but we're also interested in keeping the Gulpfile as simple as possible. It's meant to be a boilerplate, and ideally it only includes the functionality it needs to make the base framework function. With that in mind, it might be best to leave this built-in support for CSS vendor files out, since it adds a little bit more complexity to an already kinda complex build process.

**Comment by etcook** [comment]
@gakimball I'll refactor based on your previous suggestion and remove minifyCSS. Note, on my end, I actually handle vendor CSS in a separate file instead of altogether with the project CSS. This is personal decision, since I like to keep things logically separated and don't really mind the single extra CSS file that's called. Thanks for the note re: SASS not being able to import plain jane CSS. That's mindblowing to me.

**Comment by gakimball** [comment]
@etcook The technical reason is that `@import` already exists as a CSS concept, and they didn't want to overload the functionality any more than they already have. Sass 4.0 will use the term `@use`, which better separates the Sass and CSS concepts of imports.

**Comment by etcook** [comment]
@gakimball Should I close this PR out and create a new one?

**Comment by gakimball** [comment]
I have no preference, you can keep working on this one if you'd like.

**Pull request closed without merging**
